---
title: Marinheiro só
subtitle: Marin solitaire
description: Une chanson de capoeira qui conte la vie de marin
date: 2023-07-10
date-modified: 07-08-2023
license: CC BY-SA
author: 
  - Z.
  - PYM
categories: 
  - capoeira
  - chant
title-block-banner: ???
image: ???
image-alt: ???
---

INTRO

## Le chant

::: {layout-ncol=2}

### Marinheiro só 🇧🇷

| Eu não sou daqui
| **Marinheiro só**
| Eu não tenho amor
| **Marinheiro só**
| Eu sou da Bahia
| **Marinheiro só**
| De São Salvador
| **Marinheiro só**
| Mairheiro, marinheiro
| **Marinheiro só**
| Quem te ensinou a nadar
| **Marinheiro só**
| Foi o tombo do navio
| **Marinheiro só**
| Ou foi o balanço do mar
| **Marinheiro só**
| La vem, la vem,
| **Marinheiro só**
| Como ele vem façeiro
| **Marinheiro só**
| Como todo de branco
| **Marinheiro só**
| Com seu bonezinho

### Marin solitaire 🇫🇷

| Je ne suis pas d'ici
| **Marin solitaire**
| Je n'ai pas d'amour
| **Marin solitaire**
| Je suis de Bahia
| **Marin solitaire**
| De São Salvador
| **Marin solitaire**
| Marin, Marin
| **Marin solitaire**
| Qui t'a appris à nager
| **Marin solitaire**
| Etait-ce le roulis du navire
| **Marin solitaire**
| Ou était-ce la houle de la mer
| **Marin solitaire**
| Il arrive, il arrive
| **Marin solitaire**
| Comme il est coquet
| **Marin solitaire**
| Tout de blanc vêtu
| **Marin solitaire**
| Avec sa petite casquette
| **Marin solitaire**

:::

## Vidéo de référence

{{< https://www.youtube.com/watch?v=mjqG0UlpTb8 >}}

## Vocabulaire

### Noms communs

À COMPLÉTER SI TU PEUX:

| Portugais        | Français                 |
| -------------    | --------------           |
| **o Marinheiro** | Marin                    |
| **aqui**         | ici                      |
| **o navio**      | le navire                |
| **o mar**        | la mer                   |
| **o balanço**    | le balancement, la houle |
| **o boné**       | la casquette, le béret   |

### Verbes

| Portugais            | Français         | Infinitif                        |
| -------------------- | ---------------- | -------------------------------- |
| **eu sou**           | je suis          | [ser / être][ser]                |
| **foi**              | ce fut           | [ser / être][ser]                |
| **ele vem***         | il vient         | [vir / venir][vir]               |
| **Quem te ensinho**  | Qui t'a enseigné | [ensinar / enseigner][ensinar]   |
| **nadar**            | nager            | [nadar / nager][nadar]           |

[ser]: https://la-conjugaison.nouvelobs.com/portugais/verbe/ser.php
[vir]: https://la-conjugaison.nouvelobs.com/portugais/verbe/vir.php
[ensinar]: https://la-conjugaison.nouvelobs.com/portugais/verbe/ensinar.php
[nadar]: https://la-conjugaison.nouvelobs.com/portugais/verbe/nadar.php

## Culture

### Bahia

L'état de Bahia est l'un des plus grands états fédérés du Brésil. La capoeira y est, historiquement et encore aujourd'hui, très présente, et plusieurs groupes de capoeira français ou non portent d'ailleurs des noms y faisant référence.

### Salvador

Salvador, aussi appelée Salvador da Bahia, est la capitale de l'état de Bahia ; elle est également la ville de naissance de Mestre Bimba, le père de la capoeira régionale.
