---
title: Santo António eu quero água
subtitle: Saint Antoine je veux de l'eau
description: ???
date: 2023-07-10
date-modified: 11/08/2023
license: CC BY-SA
author: 
  - Z.
  - PYM
categories: 
  - capoeira
  - chant
title-block-banner: ???
image: ???
image-alt: ???
---

INTRO

## Le chant

::: {layout-ncol=2}

### Santo António eu quero água 🇧🇷

| Santo António eu quero água
|
| **Santo António eu quero água**
|
| Quero água pra beber
| Quero água pra lavar
| Quero água pra benzer
| Eu quero água
|
| **Quero água pra beber**
| **Quero água pra lavar**
| **Quero água pra benzer**
| **Eu quero água**

### Saint Antoine je veux de l'eau 🇫🇷

| Saint Antoine je veux de l'eau
|
| **Saint Antoine je veux de l'eau**
|
| Je veux de l'eau pour boire
| Je veux de l'eau pour laver
| Je veux de l'eau pour bénir
| Je veux de l'eau
|
| **Je veux de l'eau pour boire**
| **Je veux de l'eau pour laver**
| **Je veux de l'eau pour bénir**
| **Je veux de l'eau**

:::

## Vidéo de référence

{{< https://www.youtube.com/watch?v=w5t71QK-eqw >}}

## Prononciation et astuces de chant

Dans cette chanson, par souci du rythme, il est courant de ne pas respecter la présence du mot "eu" ("je"), souvent éludé, notamment dans la première phrase.

## Vocabulaire

### Noms communs

À COMPLÉTER SI TU PEUX:

| Portugais     | Français       |
| ------------- | -------------- |
| **a água**    | l'eau          |


### Verbes

| Portugais            | Français         | Infinitif                        |
| -------------------- | ---------------- | -------------------------------- |
| **Eu quero** | je veux | [querer / vouloir][querer] |
| **beber**        | boire     | [beber / boire][beber]      |
| **lavar**        | laver     | [lavar / laver][lavar]      |
| **benzer**        | bénir     | [benzer / bénir][benzer]      |

[querer]: https://la-conjugaison.nouvelobs.com/portugais/verbe/querer.php
[beber]: https://la-conjugaison.nouvelobs.com/portugais/verbe/beber.php
[lavar]: https://la-conjugaison.nouvelobs.com/portugais/verbe/lavar.php
[benzer]: https://la-conjugaison.nouvelobs.com/portugais/verbe/benzer.php

## Culture

### Santo António
